name: irp-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.10
  - numpy=1.26.4
  - pandas=2.2.3
  - scikit-learn=1.5.1
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - flask=3.1.0
  - python-dotenv=1.0.1
  - pip
  - pip:
      - gunicorn==20.1.0